package br.com.builder;

import android.content.Context;

import java.util.ArrayList;
import java.util.List;

import br.com.dao.ArvoreDAO;
import br.com.model.Arvore;

/**
 * Created by Fernando on 11/09/2016.
 */
public class ArvoreBuilder {

    private static List<Arvore> arvores;

    static {
        arvores = new ArrayList<>();
        arvores.add(new Arvore("Abiu","Lucuma torta","Sapotaceae",0.5));
        arvores.add(new Arvore("Abiu-amarelo","Pouteria caimito","Sapotaceae",0.5));
        arvores.add(new Arvore("Acacia","Cassia speciosa","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Acácia","Acacia mangium","Fabaceae",0.5));
        arvores.add(new Arvore("Acácia-monjolo","Acacia polyphylla","Fabaceae",0.5));
        arvores.add(new Arvore("Acácia-muquém","Acacia glomerosa","Fabaceae",0.5));
        arvores.add(new Arvore("Acácia-negra","Acacia mearnsii","Fabaceae",0.5));
        arvores.add(new Arvore("Açacu","Hevea spruceana","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Açaí","Euterpe oleraceae Mart.","Arecaceae",0.5));
        arvores.add(new Arvore("Açaí-da-mata","Euterpe precatoria Mart.","Arecaceae",0.5));
        arvores.add(new Arvore("Acapú","Vouacapoua pallidor","Fabaceae",0.5));
        arvores.add(new Arvore("Açoita-cavalo","Luehea divaricata","Tiliaceae",0.5));
        arvores.add(new Arvore("Açoita-cavalo-grande","Luehea candicans","Tiliaceae",0.5));
        arvores.add(new Arvore("Açoita-cavalo-graúdo","Luehea grandiflora","Tiliaceae",0.5));
        arvores.add(new Arvore("Agonandra","Agonandra excelsa","Opiliaceae",0.5));
        arvores.add(new Arvore("Agua","Chrysophyllum marginatum","Sapotaceae",0.5));
        arvores.add(new Arvore("Albízia","Albizia polycephala","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Albizia-farinha-seca","Albizia niopoides","Fabaceae",0.5));
        arvores.add(new Arvore("Albízia-jaguarana","Albizia pedicellaris","Fabaceae",0.5));
        arvores.add(new Arvore("Albízia-pupuruca","Albizia edwallii","Fabaceae",0.5));
        arvores.add(new Arvore("Aldrago","Pterocarpus violaceus","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Alecrim-de-campinas","Holocalyx balansae","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Alecrim-de-campinas","Holocalyx balansae","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Alecrim-do-campo","Baccharis dracunculifoli","Asteraceae",0.5));
        arvores.add(new Arvore("Aleluia-cascuda","Sophora tomentosa","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Algodão-do-brejo","Hibiscus tiliaceus","Malvaceae",0.5));
        arvores.add(new Arvore("Almecega","Protium heptaphyllum","Burseraceae",0.5));
        arvores.add(new Arvore("Almecegueira-do-mato-grosso","Protium spruceanum","Burseraceae",0.5));
        arvores.add(new Arvore("Amburana","Amburana cearensis","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Amburana-de-cheiro","Amburana cearensis","leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Amburana-de-cheiro","Amburana cearensis","Fabaceae",0.5));
        arvores.add(new Arvore("Amburana-rajada","Amburana cearensis","Fabaceae",0.5));
        arvores.add(new Arvore("Ameixa-de-inverno","Eriobotrya japonica","Rosaceae",0.5));
        arvores.add(new Arvore("Amendoim-Bravo","Pterogyne nitens","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Amendoim-do-campo","Pterogyne nitens","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Amendoim-falso","Acosmium subelegans","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Amescla","Trattinnickia rhoifolia","Burseraceae",0.5));
        arvores.add(new Arvore("Amesclão","Trattinnickia burserifolia","Burseraceae",0.5));
        arvores.add(new Arvore("Anaxagorea","Anaxagorea dolichocarpa","Annonaceae",0.5));
        arvores.add(new Arvore("Anda-Açu","Joannesia princeps","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Andira-araroba","Andira fraxinifolia","Fabaceae",0.5));
        arvores.add(new Arvore("Andira-da-várzea","Andira inermis","Fabaceae",0.5));
        arvores.add(new Arvore("Andira-gigante","Andira legalis","Fabaceae",0.5));
        arvores.add(new Arvore("Andirá-uxi","Andira micrantha","Fabaceae",0.5));
        arvores.add(new Arvore("Andiroba","Carapa guianensis","Meliaceae",0.5));
        arvores.add(new Arvore("Angelim","Andira","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Angelim","Andira laurifolia","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Angelim-amargoso-amarelo","Vatairea heteroptera","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-amargoso-bolacha","Vatairea guianensis","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-da-mata","Hymenolobium excelsum","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-do-cerrado","Vatairea macrocarpa","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Angelim-do-pará","Hymenolobium flavum","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-fedorento","Hymenolobium pulcherrimum","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-gracuí","Hymenolobium janeirense","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-liso","Andira inermis","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Angelim-macho","Hymenolobium  heterocarpum","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-nítida","Hymenolobium nitidum","Fabaceae",0.5));
        arvores.add(new Arvore("Angelim-pedra-falso","Hymenolobium modestum","Fabaceae",0.5));
        arvores.add(new Arvore("angelim-rajado","Zygia racemosa","Fabaceae",0.5));
        arvores.add(new Arvore("Angico branco do morro","Anadenanthera peregrina","Mimosoideae - Leguminosae",0.5));
        arvores.add(new Arvore("Angico-branco","Piptadenia macrocarpa","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Angico-bravo","Anadenanthera colubrina","Fabaceae",0.5));
        arvores.add(new Arvore("Angico-da-mata","Parapiptadenia rigida","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Angico-de-folha-fina","Pseudopiptadenia suaveolens","Fabaceae",0.5));
        arvores.add(new Arvore("Angico-do-cerrado","Anadenanthera falcata","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Angico-do-morro","Anadenanthera peregrina","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Angico-jacaré","Piptadenia gonoacantha","Fabaceae",0.5));
        arvores.add(new Arvore("Angico-monjolo","Anadenanthera colubrina","Fabaceae",0.5));
        arvores.add(new Arvore("Angico-rosa","Parapiptadenia rigida","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Angico-roxo","Parapiptadenia pterosperma","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Angico-vermelho","Anadenanthera macrocarpa","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Anona","Annona cherimola Miler","Annonaceae",0.5));
        arvores.add(new Arvore("Anona-dioica","Annona dioica","Annonaceae",0.5));
        arvores.add(new Arvore("Apê-açu","Eugenia umbelliflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá","Psidium guineense","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá amarelo","Psidium cattleyanum","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-da-mata","Myrcia citrifolia","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-da-serra","Calycorectes acutatus","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-do-mato","Myrcianthes gigantea","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-piranga","Eugenia leitonii","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçarana","Calyptranthes clusiifolia","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-rosa","Psidium cattleyanum","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-roxo","Psidium rufum","Myrtaceae",0.5));
        arvores.add(new Arvore("Araçá-roxo","Psidium myrtoides","Myrtaceae",0.5));
        arvores.add(new Arvore("Aracurana-da-serra","Hyeronima alchorneoides","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Araribá","Centrolobium tomentosum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Araribá-amarelo","Centrolobium robustum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Araribá-piloso","Centrolobium tomentosum","Fabaceae",0.5));
        arvores.add(new Arvore("Araribá-robusto","Centrolobium robustum","Fabaceae",0.5));
        arvores.add(new Arvore("Araribá-Rosa","Centrolobium tomentosum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Araticum","Annona coriacea","Annonaceae",0.5));
        arvores.add(new Arvore("Araticum","Annona cacans","Annonaceae",0.5));
        arvores.add(new Arvore("Araticum do Mato","Rollinia sylvatica","Annonaceae",0.5));
        arvores.add(new Arvore("Araticum-alvadio","Rollinia sericea","Annonaceae",0.5));
        arvores.add(new Arvore("Araticum-do-brejo","Annona glabra","Annonaceae",0.5));
        arvores.add(new Arvore("Arco-de-peneira","Cupania vernalis","Sapindaceae",0.5));
        arvores.add(new Arvore("Arco-de-pipa","Erythroxylum pulchrum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Aroeira-branca","Lithraea molleoides","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-pimenteira","Schinus terebinthifolius Raddi","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-pimenteira","Schinus terebinthifolius","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-pimenteirado-campo","Schinus weinmannifolius Engl.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-preta","Myracrodruon urundeuva","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-Salsa","Schinus molle","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-salsa","Schinus molle L.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Aroeira-verdadeiro","Myracrodruon urundeuva Allemão","Anacardiaceae",0.5));
        arvores.add(new Arvore("Árvore da Chuva","Samanea saman","Leguminosae – Caesalpinioideae",0.5));
        arvores.add(new Arvore("Assobieira","Schinus polygama","Anacardiaceae",0.5));
        arvores.add(new Arvore("Ata","Annona squamosa L.","Annonaceae",0.5));
        arvores.add(new Arvore("Axuá-torrado","Sacoglottis guianensis","Humiriaceae",0.5));
        arvores.add(new Arvore("Azevinho","Ilex microphylla Hook.","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Babaçu","Orbignya speciosa","Palmae",0.5));
        arvores.add(new Arvore("Babosa-branca","Cordia superba","Boraginaceae",0.5));
        arvores.add(new Arvore("Bacaba-de-leque","Oenocarpus distichus","Arecaceae",0.5));
        arvores.add(new Arvore("Bacaba-mapora","Oenocarpus mapora H.","Arecaceae",0.5));
        arvores.add(new Arvore("Bacaba-mirim","Oenocarpus minor","Arecaceae",0.5));
        arvores.add(new Arvore("Bacaba-patauá","Oenocarpus bataua Mart.","Arecaceae",0.5));
        arvores.add(new Arvore("Bacaba-verdadeira","Oenocarpus bacaba","Arecaceae",0.5));
        arvores.add(new Arvore("Bacupari","Garcinia gardneriana","Clusiaceae",0.5));
        arvores.add(new Arvore("Baga-de-macaco","Posoqueria acutifolia","Rubiaceae",0.5));
        arvores.add(new Arvore("Baga-de-morcego","Trichilia pallida","Meliaceae",0.5));
        arvores.add(new Arvore("Baga-de-sabiá","Acnistus arborescens","Solanaceae",0.5));
        arvores.add(new Arvore("Baguaçu","Talauma ovata","Magnoliaceae",0.5));
        arvores.add(new Arvore("Bajuruvoca","Ternstroemia brasiliensis","Theaceae",0.5));
        arvores.add(new Arvore("Balsaminho","Diptychandra aurantiaca","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Bapeba-pêssego","Pouteria venosa","Sapotaceae",0.5));
        arvores.add(new Arvore("Barbatimão","Stryphnodendron polyphyllum","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Barbatimão-branco","Stryphnodendron  pulcherrimum","Fabaceae",0.5));
        arvores.add(new Arvore("Barreiro","Machaerium hirtum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Baru","Dipteryx alata","Fabaceae",0.5));
        arvores.add(new Arvore("Batatá","Pouteria beaurepairei","Sapotaceae",0.5));
        arvores.add(new Arvore("Batitô","Myrcia acuminatissima","Myrtaceae",0.5));
        arvores.add(new Arvore("Batitô-grande","Gomidesia affinis","Myrtaceae",0.5));
        arvores.add(new Arvore("Bauhinia-Rosa","Bauhinia variegata","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Benjoeiro","Styrax pohlii","Styracaceae",0.5));
        arvores.add(new Arvore("Benjoeiro","Styrax camporum","Styracaceae",0.5));
        arvores.add(new Arvore("Benjoeiro","Styrax acuminatus","Styracaceae",0.5));
        arvores.add(new Arvore("Bico-de-pato","Machaerium acutifolium","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Bico-de-pato","Machaerium nyctitans","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Bicuíba","Virola bicuhyba","Myristicaceae",0.5));
        arvores.add(new Arvore("Bicuíba-cheirosa","Virola oleifera","Myristicaceae",0.5));
        arvores.add(new Arvore("Biribá","Annona mucosa Jacq.","Annonaceae",0.5));
        arvores.add(new Arvore("Biribá","Rollinia mucosa","Annonaceae",0.5));
        arvores.add(new Arvore("Boleiro","Alchornea Triplinervia","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Bolsa-de-pastor","Zeyheria tuberculosa","Bignoniaceae",0.5));
        arvores.add(new Arvore("Bonifácio","Maprounea guianensis","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Bracatinga","Mimosa scabrella","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Bracatinga-comum","Bracatinga-comum","Fabaceae",0.5));
        arvores.add(new Arvore("Branquilho","Sebastiania brasiliensis","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Branquinho","Sebastiania commersoniana","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Brejaúva","Astrocaryum aculeatissimum","Arecaceae",0.5));
        arvores.add(new Arvore("Breu","Protium polybotryum","Burseraceae",0.5));
        arvores.add(new Arvore("Breu-almécega","Protium heptaphyllum","Burseraceae",0.5));
        arvores.add(new Arvore("Breu-barrote","Protium puncticulatum","Burseraceae",0.5));
        arvores.add(new Arvore("Breu-do-brejo","Protium  spruceanum","Burseraceae",0.5));
        arvores.add(new Arvore("Breu-preto","Protium subserratum","Burseraceae",0.5));
        arvores.add(new Arvore("Breu-vermelho","Protium altsonii","Burseraceae",0.5));
        arvores.add(new Arvore("Buchenavia","Buchenavia rabelloana","Combretaceae",0.5));
        arvores.add(new Arvore("Buchenavia","Buchenavia kleinii","Combretaceae",0.5));
        arvores.add(new Arvore("Bugreiro","Lithraea molleoides","Anacardiaceae",0.5));
        arvores.add(new Arvore("Buriti","Mauritia flexuosa L.f.","Arecaceae",0.5));
        arvores.add(new Arvore("Buriti-bravo","Mauritiella aculeata","Arecaceae",0.5));
        arvores.add(new Arvore("Buritirana","Mauritia carana Wallace","Arecaceae",0.5));
        arvores.add(new Arvore("Buruti","Mauritia flexuosa","Palmae",0.5));
        arvores.add(new Arvore("Butiá-boneti","Butia capitata (Mart.)","Arecaceae",0.5));
        arvores.add(new Arvore("Butiá-da-praia","Butia capitata","Arecaceae",0.5));
        arvores.add(new Arvore("Cabaceira-cuité","Crescentia cujete","Compositae",0.5));
        arvores.add(new Arvore("Cabelo-de-negro","Connarus suberosus","Connaraceae",0.5));
        arvores.add(new Arvore("Cabeludinha","Myrciaria glomerata","Myrtaceae",0.5));
        arvores.add(new Arvore("Cabreúva","Myroxylon peruiferum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("cabreúva-de-bálsamo","Myrocarpus fastigiatus","Fabaceae",0.5));
        arvores.add(new Arvore("Cabreúva-parda","Myrocarpus frondosus","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Cabreúva-vermelha","Myroxylon peruiferum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Cacaueiro","Theobroma cacao","Malvaceae",0.5));
        arvores.add(new Arvore("Cadan","Anthocephalus indicus","Rubiáceae",0.5));
        arvores.add(new Arvore("Café-bravo","Guarea macrophylla","Meliaceae",0.5));
        arvores.add(new Arvore("Café-de-bugre","Cordia ecalyculata","Boraginaceae",0.5));
        arvores.add(new Arvore("Café-do-mato","Trichilia silvatica","Meliaceae",0.5));
        arvores.add(new Arvore("Cafezeiro-do-mato","Casearia decandra","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Cagaita","Eugenia dysenterica","Myrtaceae",0.5));
        arvores.add(new Arvore("Caguantã","Cupania racemosa","Sapindaceae",0.5));
        arvores.add(new Arvore("Caixeta","Didymopanax morototoni","Araliaceae",0.5));
        arvores.add(new Arvore("Caixeta","Croton salutaris","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Caixeta-mole","Croton piptocalyx","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Caixeta-mole","Croton piptocalyx","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Cajá-manga","Spondias dulcis","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cajarana","Spondias dulcis Parkinson","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cajazeira","Spondias mombin","Anacardiaceae",0.5));
        arvores.add(new Arvore("Caju","Anacardium occidentale L.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cajuçu","Anacardium parvifolium Ducke","Anacardiaceae",0.5));
        arvores.add(new Arvore("Caju-damata","Anacardium giganteum W","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cajueiro-do-campo","Canacardium humile","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cajueiro-do-campo","Anacardium humile","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cajui","spruceanum Benth ex Engl.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Calabura","Muntingia calabura","Tiliaceae",0.5));
        arvores.add(new Arvore("Caliandra-vermelha","Calliandra tweediei","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Calistemo","Callistemon speciosum","Myrtaceae",0.5));
        arvores.add(new Arvore("Camarão amarelo","Pachystachys lutea Ness","Acanthaceae",0.5));
        arvores.add(new Arvore("Camarinha","Gaylussacia brasiliensis","Ericaceae",0.5));
        arvores.add(new Arvore("Cambará","Gochnatia pulchra","Asteraceae",0.5));
        arvores.add(new Arvore("Cambará-de-lixa","Aloysia virgata","Verbenaceae",0.5));
        arvores.add(new Arvore("Cambará-guaçu","Vernonia polyanthes","Asteraceae",0.5));
        arvores.add(new Arvore("Cambará-pérola","Gochnatia polymorpha","Asteraceae",0.5));
        arvores.add(new Arvore("Camboatã-branco","Matayba juglandifolia","Sapindaceae",0.5));
        arvores.add(new Arvore("Camboatã-branco","Matayba elaeagnoides","Sapindaceae",0.5));
        arvores.add(new Arvore("Camboatã-da-serra","Connarus regnellii","Connaraceae",0.5));
        arvores.add(new Arvore("Camboim","Myrciaria delicatula","Myrtaceae",0.5));
        arvores.add(new Arvore("Cambroé","Casearia lasiophylla","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Cambuca","Plinia edulis","Myrtaceae",0.5));
        arvores.add(new Arvore("Cambucá-peixoto","Plinia rivularis","Myrtaceae",0.5));
        arvores.add(new Arvore("Cambuci","Campomanesia phaea","Myrtaceae",0.5));
        arvores.add(new Arvore("Cambuí","Myrcia multiflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Cambuí","Myrciaria tenella","Myrtaceae",0.5));
        arvores.add(new Arvore("Canafístula","Peltophorum dubium","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Candeia","Gochnatia polymorpha","Asteraceae",0.5));
        arvores.add(new Arvore("Candeia","Piptocarpha rotundifolia","Asteraceae",0.5));
        arvores.add(new Arvore("Canela","Ocotea divaricata","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-amarela","Nectandra lanceolata","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-amarela","Nectandra oppositifolia","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-batalha","Cryptocarya aschersoniana","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-branca","Nectandra membranacea","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-burra","Ocotea nectandrifolia","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-coqueiro","Ocotea catharinensis","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-da-índia","Cinnamomum zeylanicum","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-de-cheiro","Aniba firmula","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-de-veado","Helietta appiculata","Rutaceae",0.5));
        arvores.add(new Arvore("Canela-do-campo","Ocotea silvestris","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-do-cerrado","Ocotea corymbosa","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-do-mato","Nectandra nitidula","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-frade","Endlicheria paniculata","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-guaicá","Ocotea puberula","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-louro","Ocotea diospyrifolia","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-louro","Nectandra megapotamica","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-noz-moscada-do-brasil","Cryptocarya moschata","Lauraceae",0.5));
        arvores.add(new Arvore("Canelão-amarelo","Ocotea velutina","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-preta","Ocotea pulchella","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-sassafrás","Ocotea odorifera","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-sassafrás-do-campo","Ocotea elegans","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-sebo","Nectandra grandiflora","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-vassoura","Cinnamomum stenophyllum","Lauraceae",0.5));
        arvores.add(new Arvore("Canela-vassoura","Ocotea minarum","Lauraceae",0.5));
        arvores.add(new Arvore("Canelinha","Nectandra megapotamica","Lauraceae",0.5));
        arvores.add(new Arvore("Cangalheira","Lamanonia ternata","Cunoniaceae",0.5));
        arvores.add(new Arvore("Canjambo","Guarea kunthiana","Meliaceae",0.5));
        arvores.add(new Arvore("Canjarana","Cabralea canjerana","Meliaceae",0.5));
        arvores.add(new Arvore("Canjerana","Cabralea canjerana","Meliaceae",0.5));
        arvores.add(new Arvore("Cansanção","Urera baccifera","Urticaceae",0.5));
        arvores.add(new Arvore("Canudo-de-pito","Mabea brasiliensis","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Canudo-de-pito","Mabea fistulifera","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Canudo-de-pito","Senna pendula","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Canxim","Pachystroma longifolium","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Canzileiro","Platypodium elegans","Fabaceae",0.5));
        arvores.add(new Arvore("Capa-rosa","Miconia rigidiuscula","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Capa-rosa","Psychotria hoffmannseggiana","Rubiaceae",0.5));
        arvores.add(new Arvore("Capitão-do-cerrado","Terminalia argentea","Combretaceae",0.5));
        arvores.add(new Arvore("Capitão-mirindiba","Terminalia januariensis","Combretaceae",0.5));
        arvores.add(new Arvore("Capitão-tanibuco","Terminalia lucida","Combretaceae",0.5));
        arvores.add(new Arvore("Capitãozinho","Terminalia triflora","Combretaceae",0.5));
        arvores.add(new Arvore("Capixingui","Croton floribundus","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Capororoca","Rapanea umbellata","Myrsinaceae",0.5));
        arvores.add(new Arvore("Capororoca","Rapanea ferruginea","Myrsinaceae",0.5));
        arvores.add(new Arvore("Caqui","Diospyros kaki Thunb.","Ebenaceae",0.5));
        arvores.add(new Arvore("Caqui-do-mato","Diospyros brasiliensis","Ebenaceae",0.5));
        arvores.add(new Arvore("Caraipé-aracaensis","Licania aracaensis","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Caraipé-belingtoni","Licania bellingtonii","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Caraipé-mirim","Licania tomentosa","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Carapanaúba","Aspidosperma oblongum A.DC.","Apocynaceae",0.5));
        arvores.add(new Arvore("Carimã","Sparattosperma leucanthum (Vell.)","Bignoniaceae",0.5));
        arvores.add(new Arvore("Carnaúba","Copernicia prunifera","Palmae",0.5));
        arvores.add(new Arvore("Carnaubeira","Copernicia prunifera","Arecaceae",0.5));
        arvores.add(new Arvore("Caroba","Jacaranda macrantha","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caroba-brava","Dalbergia brasiliensis","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Caroba-carajasensis","Jacaranda carajasensis","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caroba-do-mato","Jacaranda macrantha","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caroba-miúda","Jacaranda micrantha","Bignoniaceae",0.5));
        arvores.add(new Arvore("Carobão","Jacaranda macrantha","Araliaceae",0.5));
        arvores.add(new Arvore("Carobão","Sciadodendron excelsum","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caroba-pará-pará","Jacaranda copaia","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caroba-rosa","Jacaranda micrantha","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caroba-roxa","Jacaranda puberula","Bignoniaceae",0.5));
        arvores.add(new Arvore("Carobinha","Jacaranda puberula","Bignoniaceae",0.5));
        arvores.add(new Arvore("Carrapateira","Ricinus communis","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Carvalho","Roupala montana","Proteaceae",0.5));
        arvores.add(new Arvore("Carvalho-brasileiro","Roupala brasiliensis","Proteaceae",0.5));
        arvores.add(new Arvore("Carvalho-brasileiro","Euplassa cantareirae","Proteaceae",0.5));
        arvores.add(new Arvore("Carvalho-da-serra","Euplassa incana","Proteaceae",0.5));
        arvores.add(new Arvore("Carvão-branco","Callisthene fasciculata","Vochysiaceae",0.5));
        arvores.add(new Arvore("Carvoeiro","Sclerolobium aureum","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Carvoeiro-angá","Tachigali denudata","Fabaceae",0.5));
        arvores.add(new Arvore("Carvoeiro-borão","Tachigali aurea","Fabaceae",0.5));
        arvores.add(new Arvore("Carvoeiro-de-folha-amanrela","Tachigali chrysophylla","Fabaceae",0.5));
        arvores.add(new Arvore("Carvoeiro-do-cerrado","Tachigali vulgaris","Fabaceae",0.5));
        arvores.add(new Arvore("Casca-branca","Rudgea viburnioides","Rubiaceae",0.5));
        arvores.add(new Arvore("Casca-d'anta","Drimys winteri","Winteraceae",0.5));
        arvores.add(new Arvore("Casca-d'anta","Rauvolfia sellowii","Apocynaceae",0.5));
        arvores.add(new Arvore("Casca-d'anta","Drymis brasiliensis","Winteraceae",0.5));
        arvores.add(new Arvore("Caseária","Casearia obliqua","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Caseária","Casearia arborea","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Cássia-amarela","Cassia leiandra","Fabaceae",0.5));
        arvores.add(new Arvore("Cássia-barbatimão","Cassia leptophylla","Fabaceae",0.5));
        arvores.add(new Arvore("Cássia-carnaval","Senna spectabilis","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Cássia-ferrugínea","Cassia ferruginea","Fabaceae",0.5));
        arvores.add(new Arvore("Cássia-fistula","Cassia ferruginea","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Cassia-grande","Cassia grandis","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Cássia-grande","Cassia grandis","Fabaceae",0.5));
        arvores.add(new Arvore("Cássia-mari-mari","Cassia moschata","Fabaceae",0.5));
        arvores.add(new Arvore("Castanha","Bombacopsis glabra","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Castanha-de-galinha","Couepia longipendula","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Castanha-do-maranhão","Bombacopsis glabra","bombacaceae",0.5));
        arvores.add(new Arvore("Castanheira","Ouratea semisserrata","Ochnaceae",0.5));
        arvores.add(new Arvore("Casuarina-Swamp-She-Oak","Casuarina equisitifolia","Casuarinaceae",0.5));
        arvores.add(new Arvore("Cateretê","Machaerium paraguariense","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Catiguá","Trichilia catigua","Meliaceae",0.5));
        arvores.add(new Arvore("Catiguá","Trichilia casaretti","Meliaceae",0.5));
        arvores.add(new Arvore("Catiguá-arco-de-peneira","Trichilia hirta","Meliaceae",0.5));
        arvores.add(new Arvore("Catiguazinho","Trichilia elegans","Meliaceae",0.5));
        arvores.add(new Arvore("Caúna","Ilex theezans","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Caúna-da-folha-miúda","Ilex pseudobuxus","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Caúna-da-serra","Ilex brevicuspis","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Caúna-lisa","Ilex amara","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Caviúna","Machaerium scleroxylon","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Caviúna-do-cerrado","Dalbergia miscolobium","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Caviúna-Paulista","Machaerium scleroxylon","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Caviúna-preta","Dalbergia nigra","Fabaceae",0.5));
        arvores.add(new Arvore("Caxeta","Tabebuia cassinoides","Bignoniaceae",0.5));
        arvores.add(new Arvore("Caxeta-amarela","Chrysophyllum gonocarpum","Sapotaceae",0.5));
        arvores.add(new Arvore("Cebolão","Phytolacca dioica","Phytolaccaceae",0.5));
        arvores.add(new Arvore("Cedrinho-japonês","Cryptomeria japonica","Cupressaceae",0.5));
        arvores.add(new Arvore("Cedro","Cedrela fissilis","Meliaceae",0.5));
        arvores.add(new Arvore("Cedro-do-brejo","Cedrela odorata","Meliaceae",0.5));
        arvores.add(new Arvore("Cedrorana","Cedrelinga cateniformis","Fabaceae",0.5));
        arvores.add(new Arvore("Cedro-rosa","Cedrela fissilis","Meliaceae",0.5));
        arvores.add(new Arvore("Cereja-do-rio-grande","Eugenia involucrata","Myrtaceae",0.5));
        arvores.add(new Arvore("Cerne-amarelo","Terminalia brasiliensis","Combretaceae",0.5));
        arvores.add(new Arvore("Chá-de-bugre","Cordia sellowiana","Boraginaceae",0.5));
        arvores.add(new Arvore("Chal-chal","Allophylus edulis","Sapindaceae",0.5));
        arvores.add(new Arvore("Chapada","Acosmium dasycarpum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Chapada-fruticosa","Sweetia fruticosa","Fabaceae",0.5));
        arvores.add(new Arvore("Chapeu-de-napoleão","Thevetia peruviana","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Charão","Rhus sucedanea","Anacardiaceae",0.5));
        arvores.add(new Arvore("Cheflera","Schefflera actinophylla (Endl.) Harms","Araliaceae",0.5));
        arvores.add(new Arvore("Chicha","Sterculia chicha","Sterculiaceae",0.5));
        arvores.add(new Arvore("Chico-pires","Leucochloron incuriale","Fabaceae",0.5));
        arvores.add(new Arvore("Chico-pires","Pithecellobium incuriale","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Chorão","Salix humboldtiana","Salicaceae",0.5));
        arvores.add(new Arvore("Chupa-ferro","Metrodorea stipularis","Rutaceae",0.5));
        arvores.add(new Arvore("Chupa-ferro","Metrodorea nigra","Rutaceae",0.5));
        arvores.add(new Arvore("Cincho","Sorocea bonplandii","Moraceae",0.5));
        arvores.add(new Arvore("Claraíba","Cordia glabrata","Boraginaceae",0.5));
        arvores.add(new Arvore("Clavija","Clavija nutans","Theophrastaceae",0.5));
        arvores.add(new Arvore("Clúsia-fluminensis","Clusia fluminensis","Clusiaceae",0.5));
        arvores.add(new Arvore("Coco","Cocos nucifera L.","Arecaceae",0.5));
        arvores.add(new Arvore("Coco","Cocos nucifera","Palmae",0.5));
        arvores.add(new Arvore("Coco-gariroba","Syagrus comosa","Arecaceae",0.5));
        arvores.add(new Arvore("Colher-de-vaqueiro","Salvertia convallariodora","Vochysiaceae",0.5));
        arvores.add(new Arvore("Congonha","Ilex cerasifolia","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Copaíba","Copaífera martii","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-angelim","Copaifera multijuga","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-clara","Copaifera duckei","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-do-cerrado","Copaifera langsdorffii","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-do-pará","Copaifera guyanensis","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-lucens","Copaifera lucens","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-marimari","Copaifera reticulata","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-preta","Copaifera trapezifolia","Fabaceae",0.5));
        arvores.add(new Arvore("Copaíba-vermelha","Copaifera langsdorffii","Fabaceae",0.5));
        arvores.add(new Arvore("Coração-de-negro","Poecilanthe parviflora","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Coração-tinto","Myrcia fallax","Myrtaceae",0.5));
        arvores.add(new Arvore("Correeiro","Diatenopteryx sorbifolia","Sapindaceae",0.5));
        arvores.add(new Arvore("Cortiça-amarela","Rollinia sylvatica","Annonaceae",0.5));
        arvores.add(new Arvore("Corticeira-da-serra","Erythrina falcata","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Corticeira-do-banhado","Erythrina crista-galli","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Couvetinga","Solanum erianthum","Solanaceae",0.5));
        arvores.add(new Arvore("Craibeira","Tabebuia aurea (Silva Manso)","Bignoniaceae",0.5));
        arvores.add(new Arvore("Crindiúva","Trema micrantha","Ulmaceae",0.5));
        arvores.add(new Arvore("Cryptomeria-Japonica","Criptoméria japonica","Taxodiaceae",0.5));
        arvores.add(new Arvore("Cuieira","Crescentia amazonica Ducke","Bignoniaceae",0.5));
        arvores.add(new Arvore("Cuinha","Maytenus robusta","Celastraceae",0.5));
        arvores.add(new Arvore("Cuitê-tingui","Crescentia cujete","Bignoniaceae",0.5));
        arvores.add(new Arvore("Cumaru-ferro","Dipteryx punctata","Fabaceae",0.5));
        arvores.add(new Arvore("Cumarurana","Dipteryx magnifica","Fabaceae",0.5));
        arvores.add(new Arvore("Cumaru-rosa","Dipteryx rosea Spruce","Fabaceae",0.5));
        arvores.add(new Arvore("Cumaru-verdadeiro","Dipteryx odorata","Fabaceae",0.5));
        arvores.add(new Arvore("Cupiúba","Goupia glabra","Goupiaceae",0.5));
        arvores.add(new Arvore("Cutieira-açu","Joannesia princeps","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Dalbergia","Dalbergia frutescens","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Dedaleiro","Lafoensia pacari","Lythraceae",0.5));
        arvores.add(new Arvore("Dedaleiro","Lafoensia pacari","Lythraceae",0.5));
        arvores.add(new Arvore("Dendê-do-pará","Elaeis oleifera (Kunth)","Arecaceae",0.5));
        arvores.add(new Arvore("Digonfia","Digomphia densicoma","Bignoniaceae",0.5));
        arvores.add(new Arvore("Dinizia-parda","Dinizia excelsa","Fabaceae",0.5));
        arvores.add(new Arvore("Duguentia-pindaíba","Duguetia lanceolata A. St.- Hil.","Annonaceae",0.5));
        arvores.add(new Arvore("Duguetia","Duguetia furfuracea","Annonaceae",0.5));
        arvores.add(new Arvore("Ébano-das-antilhas","Diosperus ebenaster","Ebenaceae",0.5));
        arvores.add(new Arvore("Embaúba","Cecropia pachystachya","Cecropiaceae",0.5));
        arvores.add(new Arvore("Embaúba","Cecropia hololeuca","Cecropiaceae",0.5));
        arvores.add(new Arvore("Embaúva-vermelha","Cecropia glazioui","Cecropiaceae",0.5));
        arvores.add(new Arvore("Embira-branca","Daphnopsis brasiliensis","Thymelaeaceae",0.5));
        arvores.add(new Arvore("Embira-de-sapo","Lonchocarpus muehlbergianus","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Embira-de-sapo","Lonchocarpus guilleminianus","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Embira-surucucu","Bocageopsis multiflora (Mart.) R.","Annonaceae",0.5));
        arvores.add(new Arvore("Embireira","Deguelia hatschbachii","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Embirinha","Lonchocarpus campestris","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Embiruçu-da-mata","Pseudobombax grandiflorum","Bombacaceae",0.5));
        arvores.add(new Arvore("Embiruçu-do-litoral","Eriotheca candolleana","Bombacaceae",0.5));
        arvores.add(new Arvore("Embiú-amarela","Guatteria citriodora","Annonaceae",0.5));
        arvores.add(new Arvore("Embiú-preta","Guatteria australis A.St.-Hil.","Annonaceae",0.5));
        arvores.add(new Arvore("Embuia","Ocotea porosa","Lauraceae",0.5));
        arvores.add(new Arvore("Entrada-abyssinica","Entada abissinica","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Envira-dura","Ephedranthus amazonicus R.E.Fr.","Annonaceae",0.5));
        arvores.add(new Arvore("Eritrina","Henriettea succosa","Fabaceae",0.5));
        arvores.add(new Arvore("Eritroxilum","Erythroxylum campestre","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Eritroxilum","Erythroxylum pelleterianum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Eritroxilum","Erythroxylum ambiguum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Erva-de-gralha","Psychotria carthagenensis","Rubiaceae",0.5));
        arvores.add(new Arvore("Erva-mate","Ilex paraguariensis","Aquifoliaceae",0.5));
        arvores.add(new Arvore("Escumilha","Lagerstroemia indica","Lythraceae",0.5));
        arvores.add(new Arvore("Espadeira-jacaré","Eperua oleifera","Fabaceae",0.5));
        arvores.add(new Arvore("Espeteiro","Casearia gossypiosperma","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Espinheira-santa","Maytenus ilicifolia","Celastraceae",0.5));
        arvores.add(new Arvore("Espinheiro","Mimosa bimucronata","Fabaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia ligustrina","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia bimarginata","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia aurata","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia klotzchiana","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia pluriflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia kleinii","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia dodoneaefolia","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia livida","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia stictosepala","Myrtaceae",0.5));
        arvores.add(new Arvore("Eugenia","Eugenia handroana","Myrtaceae",0.5));
        arvores.add(new Arvore("Falsa-aroeira-brava","Lithraea molleoides","Anacardiaceae",0.5));
        arvores.add(new Arvore("Falsa-aroeira-debugre","Lithraea brasiliensis Marchand","Anacardiaceae",0.5));
        arvores.add(new Arvore("Falsa-quina","Coussarea hydrangeifolia","Rubiaceae",0.5));
        arvores.add(new Arvore("Falso-angico-branco","Pseudopiptadenia contorta","Fabaceae",0.5));
        arvores.add(new Arvore("Falso-barbatimão","Cassia leptophylla","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Farinha-seca","Licania octandra","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Fava-amargosa","Vatairea paraensis","Fabaceae",0.5));
        arvores.add(new Arvore("Faveira","Parkia ulei","Fabaceae",0.5));
        arvores.add(new Arvore("Faveiro","Pterodon pubescens","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Faveiro-doce","Dimorphandra mollis","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Faveiro-do-cerrado","Dimorphandra mollis","Fabaceae",0.5));
        arvores.add(new Arvore("Faveiro-do-paraná","Dimorphandra exaltata","Fabaceae",0.5));
        arvores.add(new Arvore("Fedegoso","Senna occidentalis","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Fedegoso","Senna macranthera","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Feijó-laranjeira","Cordia ecalyculata","Boraginaceae",0.5));
        arvores.add(new Arvore("Figueira","Ficus pohliana","Moraceae",0.5));
        arvores.add(new Arvore("Figueira","Ficus citrifolia","Moraceae",0.5));
        arvores.add(new Arvore("Figueira","Coussapoa microcarpa","Cecropiaceae",0.5));
        arvores.add(new Arvore("Figueira","Ficus glabra","Moraceae",0.5));
        arvores.add(new Arvore("Figueira-branca","Ficus guaranitica","Moraceae",0.5));
        arvores.add(new Arvore("Figueira-da-pedra","Ficus enormis","Moraceae",0.5));
        arvores.add(new Arvore("Figueira-do-brejo","Ficus insipida","Moraceae",0.5));
        arvores.add(new Arvore("Figueira-do-mato","Oreopanax fulvum","Araliaceae",0.5));
        arvores.add(new Arvore("Figueirinha","Margaritaria nobilis","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Flanboyazinho","Caesalpinia pulcherrima","Fabaceae",0.5));
        arvores.add(new Arvore("Flomboyant amarelo","Delonix regia","Legumisae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Flor-de-pérola","Guapira opposita","Nyctaginaceae",0.5));
        arvores.add(new Arvore("Flore de abril","Dillenia indica","Dilleniaceae",0.5));
        arvores.add(new Arvore("Folha-de-bolo","Coccoloba mollis","Polygonaceae",0.5));
        arvores.add(new Arvore("Folha-de-castanha","Ouratea castanaefolia","Ochnaceae",0.5));
        arvores.add(new Arvore("Folha-de-serra","Ouratea spectabilis","Ochnaceae",0.5));
        arvores.add(new Arvore("Freijó-amarelo","Cordia alliodora","Boraginaceae",0.5));
        arvores.add(new Arvore("Freijó-cabeça-branca","Varronia  leucocephala","Boraginaceae",0.5));
        arvores.add(new Arvore("Freijó-cinza","Cordia goeldiana","Boraginaceae",0.5));
        arvores.add(new Arvore("Freijó-claraíba","Cordia glabrata","Boraginaceae",0.5));
        arvores.add(new Arvore("Freijó-de-formiga","Cordia nodosa Lam.","Boraginaceae",0.5));
        arvores.add(new Arvore("Freijó-malvão","Cordia sellowiana","Boraginaceae",0.5));
        arvores.add(new Arvore("Freijó-peteribi","Cordia trichotoma","Boraginaceae",0.5));
        arvores.add(new Arvore("Freixo whiteash","Fraxinus americana","Oleaceae",0.5));
        arvores.add(new Arvore("Fruta-de-boi","Diospyros hispida","Ebenaceae",0.5));
        arvores.add(new Arvore("Fruta-de-ema","Couepia grandiflora","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Fruta-de-lobo","Solanum lycocarpum","Solanaceae",0.5));
        arvores.add(new Arvore("Fruta-de-pomba","Erythroxylum cuneifolium","Solanaceae",0.5));
        arvores.add(new Arvore("Fruta-de-pomba","Erythroxylum deciduum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Fruta-de-pomba-do-campo","Erythroxylum suberosum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Gabiroba","Campomanesia pubescens","Myrtaceae",0.5));
        arvores.add(new Arvore("Gabiroba-árvore","Campomanesia xanthocarpa","Myrtaceae",0.5));
        arvores.add(new Arvore("Gameleira","Ficus enormis","Moraceae",0.5));
        arvores.add(new Arvore("Gamiova","Geonoma schottiana","Arecaceae",0.5));
        arvores.add(new Arvore("Garacuí","Andira anthelmia","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Garapa","Apuleia leiocarpa","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Garapeira","Apuleia leiocarpa","Fabaceae",0.5));
        arvores.add(new Arvore("Genipapinho","Tocoyena brasiliensis","Rubiaceae",0.5));
        arvores.add(new Arvore("Genipapo","Genipa americana","Rubiáceae",0.5));
        arvores.add(new Arvore("Genipapo-da-casca-lisa","Genipa infundibuliformis","Rubiaceae",0.5));
        arvores.add(new Arvore("Ginkgo-Biloba","Ginkgo Biloba","Ginkcoaceae",0.5));
        arvores.add(new Arvore("Gochnatia","Gochnatia barrosii","Asteraceae",0.5));
        arvores.add(new Arvore("Gochnatia-barrosii","Gochnatia barrosoae","Asteraceae",0.5));
        arvores.add(new Arvore("Goiaba","Psidium guajava","Myrtaceae",0.5));
        arvores.add(new Arvore("Goiaba-brava","Myrcia tomentosa","Myrtaceae",0.5));
        arvores.add(new Arvore("Goiaba-preta","Alibertia edulis","Rubiaceae",0.5));
        arvores.add(new Arvore("Goití-verdadeiro","Couepia impressa","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Gold-Coast-Mahogany","Khaya ivorensis","Meliaceae",0.5));
        arvores.add(new Arvore("Gombeira","Swartzia oblanceolata","Fabaceae",0.5));
        arvores.add(new Arvore("Gonçalo-alves","Astronium  fraxinifolium Schott","Anacardiaceae",0.5));
        arvores.add(new Arvore("Gonçalo-guaritá","Astronium graveolens Jacq.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Gonçalo-rajado","Astronium lecointei Ducke","Anacardiaceae",0.5));
        arvores.add(new Arvore("Gracuí","Hymenolobium janeirense","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Graviola","Annona muricata L.","Annonaceae",0.5));
        arvores.add(new Arvore("Gravitinga","Solanum granuloso-leprosum","Solanaceae",0.5));
        arvores.add(new Arvore("Grevilea silky oak","Grevillea robusta","Proteceae",0.5));
        arvores.add(new Arvore("Grumixama","Eugenia brasiliensis","Myrtaceae",0.5));
        arvores.add(new Arvore("Grumixameira","Eugenia brasiliensis","Myrtaceae",0.5));
        arvores.add(new Arvore("Grumixara","Galipea jasminiflora","Rutaceae",0.5));
        arvores.add(new Arvore("Guabiju","Myrcianthes pungens","Myrtaceae",0.5));
        arvores.add(new Arvore("Guabiroba","Syagrus oleraceae","Arecaceae",0.5));
        arvores.add(new Arvore("Guabiroba-branca","Campomanesia neriiflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Guabiroba-do-amazonas","Campomanesia eugenioides","Myrtaceae",0.5));
        arvores.add(new Arvore("Guaçatonga","Casearia sylvestris","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Guaiabira","Cordia americana","Boraginaceae",0.5));
        arvores.add(new Arvore("Guaiçara","Luetzelburgia auriculata","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Guaiuvira","Patagonula americana","Boraginaceae",0.5));
        arvores.add(new Arvore("Guaiuvira","Patagonula americana","Boraginaceae",0.5));
        arvores.add(new Arvore("Guamirim","Eugenia glazioviana","Boraginaceae",0.5));
        arvores.add(new Arvore("Guamirim-de-folha-fina","Myrcia rostrata","Myrtaceae",0.5));
        arvores.add(new Arvore("Guamirim-facho","Calyptranthes concinna","Myrtaceae",0.5));
        arvores.add(new Arvore("Guanandi","Calophyllum brasiliensis","Clusiaceae",0.5));
        arvores.add(new Arvore("Guaperê","Lamanonia ternata","Cunoniaceae",0.5));
        arvores.add(new Arvore("Guaperô","Clethra scabra","Clethraceae",0.5));
        arvores.add(new Arvore("Guapira","Guapira noxia","Nyctaginaceae",0.5));
        arvores.add(new Arvore("Guapuruvu","Schizolobium parahyba","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Guaraiuva","Savia dictyocarpa","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Guarantã","Ezenbeckia leiocarpa","Rutaceae",0.5));
        arvores.add(new Arvore("Guaraparim","Vantanea compacta","Humiriaceae",0.5));
        arvores.add(new Arvore("Guariroba","Syagrus oleracea","Arecaceae",0.5));
        arvores.add(new Arvore("Guaritá","Astronium graveolens","Anacardiaceae",0.5));
        arvores.add(new Arvore("Guassatonga","Casearia sylvestris","Flacourtiaceae",0.5));
        arvores.add(new Arvore("Guatambú","Aspidosperma parvifolium","Apocynaceae",0.5));
        arvores.add(new Arvore("Guatambu-oliva","Aspidosperma parvifolium","Apocynaceae",0.5));
        arvores.add(new Arvore("Guatambú-Sapo","Chrysophyllum gonocarpum","Sapotaceae",0.5));
        arvores.add(new Arvore("Guatambu-vermelho","Aspidosperma subincanum","Apocynaceae",0.5));
        arvores.add(new Arvore("Guaxupita","Esenbeckia grandiflora","Rutaceae",0.5));
        arvores.add(new Arvore("Guiné","Dendropanax cuneatus (DC.) Decne.& Planch.","Araliaceae",0.5));
        arvores.add(new Arvore("Guruguva","Lacistema lucidum","Lacistemataceae",0.5));
        arvores.add(new Arvore("Imbiruçu","Pseudobombax longiflorum","Bombacaceae",0.5));
        arvores.add(new Arvore("Imbirussú-Da-Mata","Pseudobombax grandiflorum","Bombacaceae",0.5));
        arvores.add(new Arvore("Imbuia","Ocotea porosa","Lauraceae",0.5));
        arvores.add(new Arvore("Indaiá-bacuri","Attalea phalerata Mart. ex Spreng","Arecaceae",0.5));
        arvores.add(new Arvore("Indaiá-maripa","Attalea maripa (Aubl.) Mart.","Arecaceae",0.5));
        arvores.add(new Arvore("Ingá","Inga flagelliformis","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá","Inga cylindrica","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá","Inga sellowiana","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Inga giboia","Inga fagifolia","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá-banana","Inga vera subsp. Affinis","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-bravo","Tachigali multijuga","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Ingá-chinelo","Inga cinnamomea","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-cipó","Inga striata","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-de-metro","Inga edulis","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá-de-porco","Tachigali densiflora","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-de-rio","Inga ingoides","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-feijão","Inga semialata","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-feijão","Inga marginata","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá-ferradura","Inga sessilis","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingaí-melancieira","Alexa grandiflora","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-mirim","Inga laurina","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá-piloso","Inga barbata","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingá-quatro-quinas","Inga vera","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Ingarana","Abarema jupunba","Fabaceae",0.5));
        arvores.add(new Arvore("Ingá-xixica","Inga heterophylla","Fabaceae",0.5));
        arvores.add(new Arvore("Ipê-Amarelo","Tabebuia vellosoi","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo","Tabebuia serratifolia","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-casca-lisa","Tabebuia vellosoi","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-craibeira","Tabebuia aurea","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-da-mata","Tabebuia chrysotricha","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-da-serra","Tabebuia alba","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-do-brejo","Tabebuia umbellata","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-do-cerrado","Handroanthus ochraceus","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-amarelo-piúva","Handroanthus vellosoi","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-branco","Sparattosperma leucanthum","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-branco","Tabebuia roseo-alba","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-branco-do-cerrado","Tabebuia dura","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-caroba-da-florverde","Cybistax antisyphilitica","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-caxeta","Tabebuia cassinoides","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-da-flor-verde","Cybistax antisyphilitica","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-da-serra","Handroanthus albus","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-dourado","Handroanthus chrysotrichus","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-felpudo","Zeyheria tuberculosa","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-roxo","Tabebuia impetiginosa","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-roxo","Tabebuia heptaphylla","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-roxo-de-sete-folhas","Handroanthus heptaphyllus","Bignoniaceae",0.5));
        arvores.add(new Arvore("Ipê-verde","Cybistax antisyphilitica","Bignoniaceae",0.5));
        arvores.add(new Arvore("Irtela","Hirtella gracilipes","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Itararanga","Pourouma guianensis","Cecropiaceae",0.5));
        arvores.add(new Arvore("Ixora-arbórea","Ixora gardneriana","Rubiaceae",0.5));
        arvores.add(new Arvore("Jaborandi","Pilocarpus pennatifolius","Rutaceae",0.5));
        arvores.add(new Arvore("Jaboticaba","Myrciaria trunciflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Jabuticabeira","Plinia trunciflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Jacanrandá de mimoso","Jacaranda mimosifolia","Bignoniaceae",0.5));
        arvores.add(new Arvore("Jacanrandá de minas","Jacaranda cuspidifolia","Bignoniaceae",0.5));
        arvores.add(new Arvore("Jacarandá","Machaerium floridum","Bignoniaceae",0.5));
        arvores.add(new Arvore("Jacarandá","Jacaranda cuspidifolia","Bignoniaceae",0.5));
        arvores.add(new Arvore("Jacarandá-branco","Machaerium vestitum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Jacarandá-da-bahia","Dalbergia nigra","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Jacarandá-do-campo","Platypodium elegans","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Jacarandá-do-mato","Andira fraxinifolia","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Jacarandá-paulista","Machaerium villosum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Jacaratiá","Jacaratia spinosa","Caricaceae",0.5));
        arvores.add(new Arvore("Jacaratiá-espinhosa","Jacaratia spinosa","Caricaceae",0.5));
        arvores.add(new Arvore("Jacareúba-angular","Calophyllum angulare","Burseraceae",0.5));
        arvores.add(new Arvore("Jacareúba-guanandi","Calophyllum brasiliense","Calophyllaceae",0.5));
        arvores.add(new Arvore("Jacatirão","Miconia langsdorffii","Melastomataceae",0.5));
        arvores.add(new Arvore("Jacatirão","Miconia cinnamomifolia","Melastomataceae",0.5));
        arvores.add(new Arvore("Jacatirão","Miconia cinerascens","Melastomataceae",0.5));
        arvores.add(new Arvore("Jacatirão","Tibouchina trichopoda","Melastomataceae",0.5));
        arvores.add(new Arvore("Jacatirão","Miconia cabussu","Melastomataceae",0.5));
        arvores.add(new Arvore("Jacatirão","Miconia brunnea","Melastomataceae",0.5));
        arvores.add(new Arvore("Jacatirão-do-brejo","Miconia ligustroides","Melastomataceae",0.5));
        arvores.add(new Arvore("Jambolão","Eugenia jambolana","Myrtaceae",0.5));
        arvores.add(new Arvore("Jambo-vermelho","Eugenia malacceensis","Myrtaceae",0.5));
        arvores.add(new Arvore("Jameri","Celtis iguanea","Ulmaceae",0.5));
        arvores.add(new Arvore("Jangada-brava","Heliocarpus popayanensis","Tiliaceae",0.5));
        arvores.add(new Arvore("Jaracatiá","Jacaratia spinosa","Caricaceae",0.5));
        arvores.add(new Arvore("Jasmim-manga","Plumeria rubra L.","Apocynaceae",0.5));
        arvores.add(new Arvore("Jatobá","Hymenea courbaril","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Jatobá-copaibeira","Guibourtia hymenaeifolia","Fabaceae",0.5));
        arvores.add(new Arvore("Jatobá-da-mata","Hymenaea courbaril var.","Fabaceae",0.5));
        arvores.add(new Arvore("Jatobá-do-cerrado","Hymenaea stigonocarpa","Fabaceae",0.5));
        arvores.add(new Arvore("Jatobá-do-cerrado","Hymenaea stigonocarpa","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Jatobá-pequeno","Hymenaea parvifolia","Fabaceae",0.5));
        arvores.add(new Arvore("Jatobá-vermelho","Hymenaea intermedia","Fabaceae",0.5));
        arvores.add(new Arvore("Jenipapo","Genipa americana","Rubiaceae",0.5));
        arvores.add(new Arvore("Jequitiba-branco","Cariniana estrelensis","Lecythidaceae",0.5));
        arvores.add(new Arvore("Jequitibá-branco","Cariniana estrellensis","Lecythidaceae",0.5));
        arvores.add(new Arvore("Jerivá","Syagrus romanzoffiana","Palmae",0.5));
        arvores.add(new Arvore("Juazeiro","Zizyphus joazeiro","Rhamnaceae",0.5));
        arvores.add(new Arvore("Juerana-branca","Balizia pedicellaris","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Jurubeba","Solanum paniculatum","Solanaceae",0.5));
        arvores.add(new Arvore("Jutaicica","Martiodendron elatum","Fabaceae",0.5));
        arvores.add(new Arvore("Jutaí-pororoca","Dialium guianense","Fabaceae",0.5));
        arvores.add(new Arvore("Juvá","Zanthoxylum monogynum","Rutaceae",0.5));
        arvores.add(new Arvore("Kauri-Pine","Agathis australis","Araucareaceae",0.5));
        arvores.add(new Arvore("Lapacho-coração","Poecilanthe parviflora","Fabaceae",0.5));
        arvores.add(new Arvore("Laranja-de-macaco","Posoqueria latifolia","Rubiaceae",0.5));
        arvores.add(new Arvore("Laranjeira-do-mato","Actinostemon concolor","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Laranjinha-do-mato","Eugenia speciosa","Myrtaceae",0.5));
        arvores.add(new Arvore("Leiteira-vermelha","Brosimum guianense","Moraceae",0.5));
        arvores.add(new Arvore("Leiteiro","Tabernaemontana hystrix","Apocynaceae",0.5));
        arvores.add(new Arvore("Leiteiro-branco","Micrandra elata","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Leiteiro-jasmim","Tabernaemontana hystrix Steud","Apocynaceae",0.5));
        arvores.add(new Arvore("Leiteiro-preto","Pouteria ramiflora","Sapotaceae",0.5));
        arvores.add(new Arvore("Leucena","Leucaena leucocephala","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Limoeiro","Seguieria langsdorfii","Phytolaccaceae",0.5));
        arvores.add(new Arvore("Limoeiro-do-mato","Styrax ferrugineus","Styracaceae",0.5));
        arvores.add(new Arvore("Louro","Cordia trichotoma","Boraginaceae",0.5));
        arvores.add(new Arvore("Louro-branco","Porcelia macrocarpa","Annonaceae",0.5));
        arvores.add(new Arvore("Louro-branco","Bastardiopsis densiflora","Malvaceae",0.5));
        arvores.add(new Arvore("Louro-cravo","Pimenta pseudocaryophyllus","Annonaceae",0.5));
        arvores.add(new Arvore("Louro-pardo","Cordia trichotoma","Boraginaceae",0.5));
        arvores.add(new Arvore("Louveira","Cyclolobium vecchi","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Louveira","Cyclolobium vecchii","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Macacaúba","Platymiscium trinitatis","Fabaceae",0.5));
        arvores.add(new Arvore("Macacaúba-pilosa","Platymiscium pubescens","Fabaceae",0.5));
        arvores.add(new Arvore("Macacaúba-sacambu","Platymiscium floribundum","Fabaceae",0.5));
        arvores.add(new Arvore("Macaúba","Acrocomia aculeata (Jacq.) Lodd.","Arecaceae",0.5));
        arvores.add(new Arvore("Macaúba","Acrocomia aculeata","Arecaceae",0.5));
        arvores.add(new Arvore("Macucurana","Hirtella hebeclada","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Macucurana-cinzeiro","Hirtella hebeclada","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Madiocão-calvum","Schefflera calva (Cham.) Frodin","Araliaceae",0.5));
        arvores.add(new Arvore("Magnolia-Amarela","Michelia champaca","Magnoliaceae",0.5));
        arvores.add(new Arvore("Maiate","Simira sampaioana","Rubiaceae",0.5));
        arvores.add(new Arvore("Mamão-do-mato","Carica quercifolia","Caricaceae",0.5));
        arvores.add(new Arvore("Mámea-abricó","Mammea americana","Calophyllaceae",0.5));
        arvores.add(new Arvore("Mamica-de-cadela","Zanthoxylum rhoifolium","Rutaceae",0.5));
        arvores.add(new Arvore("Mamica-de-porca","Zanthoxylum riedelianum","Rutaceae",0.5));
        arvores.add(new Arvore("Mamica-fedorenta","Zanthoxylum caribaeum","Rutaceae",0.5));
        arvores.add(new Arvore("Maminha-cadela","Brosimum gaudichaudii","Moraceae",0.5));
        arvores.add(new Arvore("Mamoeiro-do-campo","Carica quercifolia","Caricaceae",0.5));
        arvores.add(new Arvore("Mamoninha-do-mato","Esenbeckia febrifuga","Rutaceae",0.5));
        arvores.add(new Arvore("Manacá","Tibouchina stenocarpa","Melastomataceae",0.5));
        arvores.add(new Arvore("Manacá-da-serra","Tibouchina mutabilis","Melastomataceae",0.5));
        arvores.add(new Arvore("Manacá-de-cheiro","Brunfelsia uniflora","Solanaceae",0.5));
        arvores.add(new Arvore("Manacá-de-minas","Tibouchina sellowiana","Melastomataceae",0.5));
        arvores.add(new Arvore("Mandiocão-docerrado","Schefflera macrocarpa","Araliaceae",0.5));
        arvores.add(new Arvore("Mandioqueiro","Didymopanax morototonii","Araliaceae",0.5));
        arvores.add(new Arvore("Mandioqueiro-do-cerrado","Didymopanax macrocarpum","Araliaceae",0.5));
        arvores.add(new Arvore("Mangabeira","Hancornia speciosa Gomes","Apocynaceae",0.5));
        arvores.add(new Arvore("Mangabeira","Hancornia speciosa","Apocynaceae",0.5));
        arvores.add(new Arvore("Mangiribá","Cenostigma tocantinum","Fabaceae",0.5));
        arvores.add(new Arvore("Mangue-branco","Laguncularia racemosa","Combretaceae",0.5));
        arvores.add(new Arvore("Manguerana","Clusia criuva","Clusiaceae",0.5));
        arvores.add(new Arvore("Mangue-vermelho","Rhizophora mangle","Rhizophoraceae",0.5));
        arvores.add(new Arvore("Marajá","Bactris maraja Mart.","Arecaceae",0.5));
        arvores.add(new Arvore("Maria-faceira","Pisonia ambigua","Nyctaginaceae",0.5));
        arvores.add(new Arvore("Maria-mole","Guapira nitida","Araliaceae",0.5));
        arvores.add(new Arvore("Maria-mole","Dendropanax cuneatum","Nyctaginaceae",0.5));
        arvores.add(new Arvore("Marianeira","Acnistus arborescens","Solanaceae",0.5));
        arvores.add(new Arvore("Maria-pobre","Dilodendrom bipinnatum","Sapindaceae",0.5));
        arvores.add(new Arvore("Maricá","Mimosa bimucronata","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Marinheiro","Guarea guidonia","Meliaceae",0.5));
        arvores.add(new Arvore("Marmelada","Amaioua intermedia","Rubiaceae",0.5));
        arvores.add(new Arvore("Marmeleiro","Ruprechtia laxiflora","Polygonaceae",0.5));
        arvores.add(new Arvore("Marmeleiro-do-campo","Austroplenckia populnea","Celastraceae",0.5));
        arvores.add(new Arvore("Marmelinho","Diospyros inconstans","Ebenaceae",0.5));
        arvores.add(new Arvore("Marmelinho-do-cerrado","Licania humilis","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Marmelo","Alibertia macrophylla","Rubiaceae",0.5));
        arvores.add(new Arvore("Marmelo-do-cerrado","Alibertia sessilis","Rubiaceae",0.5));
        arvores.add(new Arvore("Marmelo-do-mangue","Dalbergia ecastophyllum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Marôlo","Annona crassiflora","Annonaceae",0.5));
        arvores.add(new Arvore("Marolo-do-cerrado","Annona cornifolia","Annonaceae",0.5));
        arvores.add(new Arvore("Mata-pasto","Senna alata","Leguminosae-Caesalpinoidea",0.5));
        arvores.add(new Arvore("Maytenus","Maytenus gonoclada","Celastraceae",0.5));
        arvores.add(new Arvore("Maytenus","Maytenus evonymoides","Celastraceae",0.5));
        arvores.add(new Arvore("Maytenus","Maytenus salicifolia","Celastraceae",0.5));
        arvores.add(new Arvore("Maytenus","Maytenus aquifolium","Celastraceae",0.5));
        arvores.add(new Arvore("Maytenus","Maytenus obtusifolia","Celastraceae",0.5));
        arvores.add(new Arvore("Mercurinho","Erythroxylum tortuosum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Mercúrio-branco","Erythroxylum argentinum","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Mirindiba-branca","Terminalia januariensis","Combretaceae",0.5));
        arvores.add(new Arvore("Mirindiba-Rosa","Lafoensia glyptocarpa","Lythraceae",0.5));
        arvores.add(new Arvore("Mocitaíba","Zollernia glabra","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("mocitaíba-do-pará","Zollernia paraensis","Fabaceae",0.5));
        arvores.add(new Arvore("Moço-mole","Guapira graciliflora","Nyctaginaceae",0.5));
        arvores.add(new Arvore("Mogno","Swietenia macrophylla","Meliaceae",0.5));
        arvores.add(new Arvore("Monguba","Pachira aquatica","Bombacaceae",0.5));
        arvores.add(new Arvore("Monjoleiro","Acacia polyphylla","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Muchita","Byrsonima ligustrifolia","Malpighiaceae",0.5));
        arvores.add(new Arvore("Mucurão","Poupartia amazonica Ducke","Anacardiaceae",0.5));
        arvores.add(new Arvore("Mulungu-crista-de-galo","Erythrina crista-galli","Fabaceae",0.5));
        arvores.add(new Arvore("Mulungu-da-serra","Erythrina falcata","Fabaceae",0.5));
        arvores.add(new Arvore("Mulungu-do-litoral","Erythrina speciosa","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Mulungu-sanaduva","Erythrina fusca","Fabaceae",0.5));
        arvores.add(new Arvore("Mulungu-suinã","Erythrina verna","Fabaceae",0.5));
        arvores.add(new Arvore("Mulungu-velutina","Erythrina velutina","Fabaceae",0.5));
        arvores.add(new Arvore("Murici","Byrsonima intermedia","Malpighiaceae",0.5));
        arvores.add(new Arvore("Murici","Byrsonima basiloba","Malpighiaceae",0.5));
        arvores.add(new Arvore("Murici","Byrsonima verbascifolia","Malpighiaceae",0.5));
        arvores.add(new Arvore("Murici-do-cerrado","Byrsonima coccolobifolia","Malpighiaceae",0.5));
        arvores.add(new Arvore("Murici-miúdo","Byrsonima sericea","Malpighiaceae",0.5));
        arvores.add(new Arvore("Murta","Murraya exotica","Rutaceae",0.5));
        arvores.add(new Arvore("Murta","Blepharocalyx salicifolius","Myrtaceae",0.5));
        arvores.add(new Arvore("Murta","Eugenia sulcata","Myrtaceae",0.5));
        arvores.add(new Arvore("Murumuru","Astrocaryum murumuru Mart.","Arecaceae",0.5));
        arvores.add(new Arvore("Mutamba-preta","Guazuma ulmifolia","Sterculiaceae",0.5));
        arvores.add(new Arvore("Mututurana","Thyrsodium spruceanum Benth.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Myrcia","Myrcia bella","Myrtaceae",0.5));
        arvores.add(new Arvore("Myrcia","Myrcia arborescens","Myrtaceae",0.5));
        arvores.add(new Arvore("Myrcia","Myrcia albo-tomentosa","Myrtaceae",0.5));
        arvores.add(new Arvore("Norfolk-Island-Pine","Araucária heterophylla","Araucareaceae",0.5));
        arvores.add(new Arvore("Ocotea","Ocotea aciphylla","Lauraceae",0.5));
        arvores.add(new Arvore("Oiti","Licania tomentosa","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Oiti-coró","Couepia rufa","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Oiti-da-praia","Couepia ovalifolia","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Oiti-do-sertão","Couepia grandiflora","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Oiti-pajurá","Couepia bracteosa","Chrysobalanaceae",0.5));
        arvores.add(new Arvore("Óleo-de-copaíba","Copaifera langsdorffii","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Óleo-pardo","Myrocarpus frondosus","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Olho-de-cabra","Ormosia arborea","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Olho-de-cabra-azul","Abarema brachystachya","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Osso-de-burro","Helietta apiculata","Rutaceae",0.5));
        arvores.add(new Arvore("Pacová-de-macaco","Swartzia langsdorffii","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Paineira","Chorisia speciosa","Bombacaceae",0.5));
        arvores.add(new Arvore("Paineira-amarela","Ceiba rivieri","Bombacaceae",0.5));
        arvores.add(new Arvore("Paineira-Branca","Chorissia specosa alba","bombacaceae",0.5));
        arvores.add(new Arvore("Paineira-do-campo","Eriotheca gracilipes","Bombacaceae",0.5));
        arvores.add(new Arvore("Paineirinha-vermelha","Spirotheca passifloroides","Bombacaceae",0.5));
        arvores.add(new Arvore("Palmeira-acumã","Syagrus flexuosa","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-aricanguinha","Geonoma elegans","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-butiá-do-cerrado","Butia paraguayenses","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-coco-amargoso","Syagrus pseudococos","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-coco-da-chapada","Allagoptera leucocalyx","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-coco-da-praia","Allagoptera arenaria","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-coco-de-natal","Bactris setosa","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-gamiova","Geonoma gamiova","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-içá","Lytocaryum hoehnei","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-indaiá-açu","Attalea dubia","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-indaiá-do-cerrado","Attalea geraensis","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeira-ouricana","Geonoma brevispatha","Arecaceae",0.5));
        arvores.add(new Arvore("Palmeirinha","Lytocaryum weddellianum","Arecaceae",0.5));
        arvores.add(new Arvore("Palmito-juçara","Euterpe edulis","Arecaceae",0.5));
        arvores.add(new Arvore("Papa-güela","Gomidesia fenzliana","Myrtaceae",0.5));
        arvores.add(new Arvore("Paratecoma-peroba","Paratecoma peroba","Bignoniaceae",0.5));
        arvores.add(new Arvore("Paratudo","Hortia arborea","Rutaceae",0.5));
        arvores.add(new Arvore("Paricá","Schizolobium parayba","Fabaceae",0.5));
        arvores.add(new Arvore("Passuaré","Sclerolobium denudatum","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pasu-taquara","Aparisthmium cordatum","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Pata-de-vaca","Bauhinia rufa","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pata-de-vaca-do-campo","Bauhinia longifolia","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pata-de-vaca-do-cerrado","Bauhinia holophylla","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau ferro-do-rio-Gr","Myracrodruon balançae","Anacardiaceae",0.5));
        arvores.add(new Arvore("Pau-alecrim","Holocalyx balansae","Fabaceae",0.5));
        arvores.add(new Arvore("Pau-amendoim","Pterogyne nitens","Fabaceae",0.5));
        arvores.add(new Arvore("Pau-Brasil","Caesalpinia echinata","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau-brasil","Caesalpinia echinata","Fabaceae",0.5));
        arvores.add(new Arvore("Pau-cigarra","Senna multijuga","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau-d'alho","Gallesia integrifolia","Phytolaccaceae",0.5));
        arvores.add(new Arvore("Pau-de-alho","Gallesia integrifolia","Phytolaccaceae",0.5));
        arvores.add(new Arvore("Pau-de-angu","Machaerium aculeatum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Pau-de-cigarra","Senna multijuga","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau-de-ferro","Caesalpinia leiostahya","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau-de-lacre","Vismia brasiliensis","Clusiaceae",0.5));
        arvores.add(new Arvore("Pau-de-leite","Sapium glandulatum","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Pau-de-mastro","Xylopia brasiliensis","Annonaceae",0.5));
        arvores.add(new Arvore("Pau-de-pilão","Callisthene minor","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-de-porco","Bursera simaruba","Burseraceae",0.5));
        arvores.add(new Arvore("Pau-de-ripa","Acrocarpus fraxinifolius","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau-de-rosas","Physocalymma scaberrimum","Lythraceae",0.5));
        arvores.add(new Arvore("Pau-de-tucano","Qualea multiflora","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-de-tucano","Vochysia tucanorum","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-de-vinho","Vochysia bifalcata","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-ferro-ferrea","Libidibia ferrea","Fabaceae",0.5));
        arvores.add(new Arvore("Pau-formiga","Triplaris brasiliana","Polygonaceae",0.5));
        arvores.add(new Arvore("Pau-formiga-branco","Triplaris surinamensis","Polygonaceae",0.5));
        arvores.add(new Arvore("Pau-incenso","Pitosporum undulatum","Pittosporaceae",0.5));
        arvores.add(new Arvore("Pau-jacaré","Piptadenia gonoacantha","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Pau-jangada","Alchornea triplinervia","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Pau-jantar-do-litoral","Zollernia falcata","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Pau-macuco","Meliosma sellowii","Sabiaceae",0.5));
        arvores.add(new Arvore("Pau-magro","Cupania oblongifolia","Sapindaceae",0.5));
        arvores.add(new Arvore("Pau-marfim","Balfourodendron riedellianum","Rutaceae",0.5));
        arvores.add(new Arvore("Pau-marfim","Balfourodendron riedelianum","Rutaceae",0.5));
        arvores.add(new Arvore("Pau-novo","Vochysia magnifica","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-para-tudo","Capsicodendron dinisii","Canellaceae",0.5));
        arvores.add(new Arvore("Pau-pereira","Platycyamus regnellii","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Pau-pereira-amarelo","Geissospermum sericeum Miers","Apocynaceae",0.5));
        arvores.add(new Arvore("Pau-pombo","Tapirira obtusa","Anacardiaceae",0.5));
        arvores.add(new Arvore("Pau-rei","Sterculia striata","Sterculiaceae",0.5));
        arvores.add(new Arvore("Pau-rosa","Aniba roseodora","Lauraceae",0.5));
        arvores.add(new Arvore("Pau-roxo","Peltogyne catingae var.","Fabaceae",0.5));
        arvores.add(new Arvore("Pau-roxo-mulato","Peltogyne paniculata","Fabaceae",0.5));
        arvores.add(new Arvore("Pau-sangue","Pterocarpus rohrii","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Pau-sangue","Machaerium brasiliense","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Pau-santo","Kielmeyera marauensis","Guttiferae",0.5));
        arvores.add(new Arvore("Pau-santo","Kielmeyera variabilis","Clusiaceae",0.5));
        arvores.add(new Arvore("Pau-terra","Qualea grandiflora","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-terra-mirim","Qualea dichotoma","Vochysiaceae",0.5));
        arvores.add(new Arvore("Pau-Viola","Cytharexyllum myrianthum","Verbenaceae",0.5));
        arvores.add(new Arvore("Paxiúba","Socratea exorrhiza","Arecaceae",0.5));
        arvores.add(new Arvore("Pê-amarelo-de-poços-de-caldas","Tabebuia alba","Bignoniaceae",0.5));
        arvores.add(new Arvore("Pé-de-coelho","Malouetia arborea","Apocynaceae",0.5));
        arvores.add(new Arvore("Peito-de-pomba","Tapirira guianensis","Anacardiaceae",0.5));
        arvores.add(new Arvore("Pequi","Caryocar brasiliense","Caryocaraceae",0.5));
        arvores.add(new Arvore("Pequiarana-da-terrafirme","Caryocar glabrum","Caryocaraceae",0.5));
        arvores.add(new Arvore("Pequi-vinagreiro","Caryocar edule","Caryocaraceae",0.5));
        arvores.add(new Arvore("Pequizeiro","Caryocar brasiliense","Caryocaraceae",0.5));
        arvores.add(new Arvore("Peroba","Aspidosperma spruceanum Benth. ex Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-amarelo","Aspidosperma ramiflorum Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-amargo","Aspidosperma cuspa (Kunth) S.F. Blake ex Pittier","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-cetim","Aspidosperma eburneum Allemão ex Saldanha","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-da-praia","Aspidosperma parvifolium A.DC.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-de-rego","Aspidosperma discolor A. DC.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-do-campo","Aspidosperma tomentosum","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-do-campo","Paratecoma peroba","Bignoniaceae",0.5));
        arvores.add(new Arvore("Peroba-do-cerrado","Aspidosperma macrocarpon Mart.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-guatambu","Aspidosperma olivaceum Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-marfim","Aspidosperma album Bernoist ex. Pichon","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-marfim-roxo","Aspidosperma desmanthum Benth. ex Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-osso","Aspidosperma cylindrocarpon Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-poca","Aspidosperma cylindrocarpon","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-rosa","Aspidosperma polyneuron Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Peroba-rosa","Aspidosperma polyneuron","Apocynaceae",0.5));
        arvores.add(new Arvore("Pêssego-do-mato","Hexachlamys edulis","Myrtaceae",0.5));
        arvores.add(new Arvore("Pessegueiro-bravo","Prunus myrtifolia","Rosaceae",0.5));
        arvores.add(new Arvore("Piaçava","Leopoldinia piassaba","Arecaceae",0.5));
        arvores.add(new Arvore("Pimenta-de-macaco","Xylopia aromática","Annonaceae",0.5));
        arvores.add(new Arvore("Pimentinha","Erythroxylum amplifolium","Erythroxylaceae",0.5));
        arvores.add(new Arvore("Pindaíba-d'água","Xylopia emarginata","Annonaceae",0.5));
        arvores.add(new Arvore("Pindaíba-preta","Xylopia emarginata Mart.","Annonaceae",0.5));
        arvores.add(new Arvore("Pindaíva","Duguetia lanceolata","Annonaceae",0.5));
        arvores.add(new Arvore("Pindaúva-fêmea","Xylopia langsdorffiana","Annonaceae",0.5));
        arvores.add(new Arvore("Pindaúva-preta","Guatteria nigrescens","Annonaceae",0.5));
        arvores.add(new Arvore("Pinha-do-brejo","Talauma ovata","Magnoliaceae",0.5));
        arvores.add(new Arvore("Piptocarpa","Piptocarpha macropoda","Asteraceae",0.5));
        arvores.add(new Arvore("Piquiá-verdadeiro","Caryocar villosum","Caryocaraceae",0.5));
        arvores.add(new Arvore("Piracanto","Piracantha coceineta","Rosaceae",0.5));
        arvores.add(new Arvore("Pitanga","Eugenia uniflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Pitanga-preta","Eugenia florida","Myrtaceae",0.5));
        arvores.add(new Arvore("Pitanga-verde","Eugenia multicostata","Myrtaceae",0.5));
        arvores.add(new Arvore("Pitangueira","Eugenia uniflora","Myrtaceae",0.5));
        arvores.add(new Arvore("Pitombeira","Talisia esculenta","Sapindaceae",0.5));
        arvores.add(new Arvore("Piúna","Terminalia januariensis","Combretaceae",0.5));
        arvores.add(new Arvore("Pixirica-branca","Clidemia biserrata","Melastomataceae",0.5));
        arvores.add(new Arvore("Pororoca","Rapanea guyanensis","Myrsinaceae",0.5));
        arvores.add(new Arvore("Primavera-arbórea","Bougainvillea glabra","Nyctaginaceae",0.5));
        arvores.add(new Arvore("Pupunha","Bactris gasipaes Kunth","Arecaceae",0.5));
        arvores.add(new Arvore("Quaresmeira","Tibouchina granulosa","Melastomaceae",0.5));
        arvores.add(new Arvore("Quaresmeira-roxa","Tibouchina granulosa","Melastomataceae",0.5));
        arvores.add(new Arvore("Quebracho-vermelho","Schinopsis brasiliensis Engl.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Quebra-machado","Trichilia clausseni","Meliaceae",0.5));
        arvores.add(new Arvore("Quina","Strychnos pseudoquina","Loganiaceae",0.5));
        arvores.add(new Arvore("Quina-de-santa-catarina","Bathysa australis","Rubiaceae",0.5));
        arvores.add(new Arvore("Quina-de-são-paulo","Solanum pseudoquina","Solanaceae",0.5));
        arvores.add(new Arvore("Quina-de-são-paulo","Alseis floribunda","Rubiaceae",0.5));
        arvores.add(new Arvore("Quina-doce","Vochysia cinnamomea","Vochysiaceae",0.5));
        arvores.add(new Arvore("Rabo-de-bugio","Alchomea glandulosa","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Rabo-de-cotia-amarelo","Stifftia chrysantha","Asteraceae",0.5));
        arvores.add(new Arvore("Rabo-de-tucano","Vochysia oppugnata","Vochysiaceae",0.5));
        arvores.add(new Arvore("Raposeira-branca","Abarema langsdorffii","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Rosa-do-campo","Kielmeyera rubriflora","Clusiaceae",0.5));
        arvores.add(new Arvore("Roxinho","Peltogyne maranhensis","Fabaceae",0.5));
        arvores.add(new Arvore("Rudgea","Rudgea jasminoides","Rubiaceae",0.5));
        arvores.add(new Arvore("Sacambu","Platymiscium floribundum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Saco-de-bode","Zeyheria digitalis","Bignoniaceae",0.5));
        arvores.add(new Arvore("Saguaragi-amarelo","Rhamnidium elaeucarpum","Rhamnaceae",0.5));
        arvores.add(new Arvore("Saguaragi-cubano","Colubrina arborea","Rhamnaceae",0.5));
        arvores.add(new Arvore("Saguaragi-vermelho","Colubrina glandulosa","Rhamnaceae",0.5));
        arvores.add(new Arvore("Saguaraji-amarelo","Rhamnidium elaeocarpum","Rhamnaceae",0.5));
        arvores.add(new Arvore("Salta-martim","Strychnos brasiliensis","Loganiaceae",0.5));
        arvores.add(new Arvore("Samaneiro-de-cangalha","Samanea tubulosa","Fabaceae",0.5));
        arvores.add(new Arvore("Sambacuim","Schefflera morototoni","Araliaceae",0.5));
        arvores.add(new Arvore("Sangra-d'água","Croton urucurana","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Sangue-de-drago","Croton macrobothrys","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Sansão-do-campo","Mimosa caesalpiniifolia","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Sapobemba","Eriotheca pentaphylla","Bombacaceae",0.5));
        arvores.add(new Arvore("Sapopema","Sloanea monosperma","Elaeocarpaceae",0.5));
        arvores.add(new Arvore("Sapopemba","Sloanea hirsuta","Elaeocarpaceae",0.5));
        arvores.add(new Arvore("Sapucaia","Lecythis pisonis","Lecythidaceae",0.5));
        arvores.add(new Arvore("Sapupira-da-mata","Bauhinia longifolia","Fabaceae",0.5));
        arvores.add(new Arvore("Sapuva","Machaerium stipitatum","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Sena-fedegosão","Senna macranthera","Fabaceae",0.5));
        arvores.add(new Arvore("Sena-multijuga","Senna multijuga","Fabaceae",0.5));
        arvores.add(new Arvore("Sena-ocidentális","Senna occidentalis","Fabaceae",0.5));
        arvores.add(new Arvore("Seringueira","Hevea brasiliensis","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Seringueira-branca","Hevea benthamiana","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Seringueira-itaúba","Hevea guianensis","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Seringueira-mirim","Hevea camargoana","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Sete-capotes","Campomanesia guazumaefolia","Myrtaceae",0.5));
        arvores.add(new Arvore("Sibipiruna","Caesalpinia peltophoroides","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Sinamão","Melia azedarach","Meliaceae",0.5));
        arvores.add(new Arvore("Siparuna","Siparuna guianensis","Monimiaceae",0.5));
        arvores.add(new Arvore("Siputá","Salacia elliptica","Hippocrateaceae",0.5));
        arvores.add(new Arvore("Siriguela","Spondias purpurea L.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Sloanea","Sloanea guianensis","Elaeocarpaceae",0.5));
        arvores.add(new Arvore("Sobrasil","Colubrina glandulosa","Rhamnaceae",0.5));
        arvores.add(new Arvore("Sombra-de-vaca","Clitoria fairchildiana","Fabaceae",0.5));
        arvores.add(new Arvore("Sorva-grande","Couma macrocarpa Barb. Rodr.","Apocynaceae",0.5));
        arvores.add(new Arvore("Sorva-miúda","Couma utilis (Mart.) Müll. Arg.","Apocynaceae",0.5));
        arvores.add(new Arvore("Spatodea","Spathodea campanulata","Bignoniaceae",0.5));
        arvores.add(new Arvore("Sucupira amarela","Sweetia fruticosa","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Sucupira-branca","Pterodon pubescens","Fabaceae",0.5));
        arvores.add(new Arvore("Sucupira-chorona","Andira unifoliolata","Fabaceae",0.5));
        arvores.add(new Arvore("Sucupira-lisa","Pterodon emarginatus","Fabaceae",0.5));
        arvores.add(new Arvore("Sucupirana","Sweetia fruticosa","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Sucupira-preta","Bowdichia virgilioides","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Sucupira-vermelha","Andira parviflora","Fabaceae",0.5));
        arvores.add(new Arvore("Suinã","Erythrina verna","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Suinã-da-serra","Erythrina verna","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Suinã-matogrossensa","Erythrina mulungu","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Sumauma","Ceiba pentandra","Bombacaceae",0.5));
        arvores.add(new Arvore("Sumaúma(Kapok-Tree)","Bombax ceiba","Bombaceae",0.5));
        arvores.add(new Arvore("Taiúva","Maclura tinctoria","Moraceae",0.5));
        arvores.add(new Arvore("Tamanqueira","Pera glabrata","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Tamanqueiro","Aegiphila sellowiana","Verbenaceae",0.5));
        arvores.add(new Arvore("Tamanqueiro-do-cerrado","Aegiphila lhotzkiana","Verbenaceae",0.5));
        arvores.add(new Arvore("Tamarindo","Tamarindus indica","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Tamboril","Enterolobium contortisiliquum","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Tamboril-brinco-de-macaco","Enterolobium glaziovii","Fabaceae",0.5));
        arvores.add(new Arvore("Tamboril-da-mata","Enterolobium contortisiliquum","Fabaceae",0.5));
        arvores.add(new Arvore("Tamboril-do-cerrado","Enterolobium gummiferum","Fabaceae",0.5));
        arvores.add(new Arvore("Tamboril-orelha-de-macaco","Enterolobium schomburgkii","Fabaceae",0.5));
        arvores.add(new Arvore("Tanheiro","Alchornea glandulosa","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Taperebá. cajá-mirim","Spondias mombin L.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Tapiá-guaçu","Alchornea sidifolia","Euphorbiaceae",0.5));
        arvores.add(new Arvore("Tapirira","Tapirira guianensis Aubl.","Anacardiaceae",0.5));
        arvores.add(new Arvore("Tapororoca-miúda","Rapanea parvifolia","Myrsinaceae",0.5));
        arvores.add(new Arvore("Tapororoca-rosa","Cybianthus peruvianus","Myrsinaceae",0.5));
        arvores.add(new Arvore("Tarumã","Vitex megapotamica","Verbenaceae",0.5));
        arvores.add(new Arvore("Tarumã-da-várzea","Vitex cymosa","Verbenaceae",0.5));
        arvores.add(new Arvore("Tarumarana","Terminalia","buchenavia",0.5));
        arvores.add(new Arvore("Taxi-ingá","Tachigali multijuga","Fabaceae",0.5));
        arvores.add(new Arvore("Teca","Tectona grandis","Verbenaceae",0.5));
        arvores.add(new Arvore("Tembetari","Zanthoxylum fagara","Rutaceae",0.5));
        arvores.add(new Arvore("Tento-da-campina","Ormosia holerythra","Fabaceae",0.5));
        arvores.add(new Arvore("Tento-de-friburgo","Ormosia friburgensis","Fabaceae",0.5));
        arvores.add(new Arvore("Tento-estipularis","Ormosia stipularis","Fabaceae",0.5));
        arvores.add(new Arvore("Tento-fastigiata","Ormosia fastigiata","Fabaceae",0.5));
        arvores.add(new Arvore("Tento-vermelho","Ormosia arborea","Fabaceae",0.5));
        arvores.add(new Arvore("Tiborna","Himatanthus obovatus","Apocynaceae",0.5));
        arvores.add(new Arvore("Tiborna-sucuúba","Himatanthus sucuuba","Apocynaceae",0.5));
        arvores.add(new Arvore("Timbó","Lonchocarpus subglaucescens","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Timburi-do-cerrado","Enterolobium gummiferum","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Tinge-cuia","Agonandra brasiliensis","Opiliaceae",0.5));
        arvores.add(new Arvore("Tingui","Magonia pubescens","Sapindaceae",0.5));
        arvores.add(new Arvore("Tingui-preto","Dictyoloma vandellianum","Rutaceae",0.5));
        arvores.add(new Arvore("Tipa-branca","Tipuana tipú","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Trichilia","Trichilia emarginata","Meliaceae",0.5));
        arvores.add(new Arvore("Tucaneiro","Citharexylum myrianthum","Verbenaceae",0.5));
        arvores.add(new Arvore("Tucumã-brejaúva","Astrocaryum aculeatissimum","Arecaceae",0.5));
        arvores.add(new Arvore("Tucumã-do-amazônas","Astrocaryum vulgare","Arecaceae",0.5));
        arvores.add(new Arvore("Tucumã-grande","Astrocaryum aculeatum G. Mey","Arecaceae",0.5));
        arvores.add(new Arvore("Umbu","Spondias tuberosa Arruda","Anacardiaceae",0.5));
        arvores.add(new Arvore("Unha-de-vaca","Bauhinia forficata","Leguminosae-Caesalpinoideae",0.5));
        arvores.add(new Arvore("Unha-de-vaca-de-espinho","Bauhinia forficata","Fabaceae",0.5));
        arvores.add(new Arvore("Unha-de-vaca-do-campo","Bauhinia longifolia","Fabaceae",0.5));
        arvores.add(new Arvore("Unha-de-vaca-miúda","Bauhinia brevipes","Fabaceae",0.5));
        arvores.add(new Arvore("Unha-de-vaca-mororó","Bauhinia cheilantha","Fabaceae",0.5));
        arvores.add(new Arvore("Urucum","Bixa orelana","Bixaceae",0.5));
        arvores.add(new Arvore("Urucum-da-mata","Bixa arborea Huber","Bixaceae",0.5));
        arvores.add(new Arvore("Urucurana","Sloanea terniflora","Elaeocarpaceae",0.5));
        arvores.add(new Arvore("Uvaia","Eugenia pyriformis","Myrtaceae",0.5));
        arvores.add(new Arvore("Uva-Japão","Hovenia dulcis","Rhamnaceae",0.5));
        arvores.add(new Arvore("Uxi-verdadeiro","Uxi-verdadeiro","Humiriaceae",0.5));
        arvores.add(new Arvore("Vassourão-branco","Piptocarpha axillaris","Asteraceae",0.5));
        arvores.add(new Arvore("Vassourão-preto","Vernonia discolor","Asteraceae",0.5));
        arvores.add(new Arvore("Vassoura-vermelha","Dodonea viscosa","Sapindaceae",0.5));
        arvores.add(new Arvore("Veludo","Sclerolobium paniculatum","Rubiaceae",0.5));
        arvores.add(new Arvore("Vernonia","Vernonia ferruginea","Asteraceae",0.5));
        arvores.add(new Arvore("Vinhático","Plathymenia reticulata","Leguminosae-Mimosoideae",0.5));
        arvores.add(new Arvore("Vinhático-da-mata","Plathymenia reticulata","Fabaceae",0.5));
        arvores.add(new Arvore("Visgueiro-bandarra","Parkia paraensis","Fabaceae",0.5));
        arvores.add(new Arvore("Visgueiro-benguê","Parkia multijuga","Fabaceae",0.5));
        arvores.add(new Arvore("Visgueiro-bolota","Parkia pendula","Fabaceae",0.5));
        arvores.add(new Arvore("Visgueiro-do-igapó","Parkia discolor","Fabaceae",0.5));
        arvores.add(new Arvore("Visgueiro-esponja","Parkia nitida","Fabaceae",0.5));
        arvores.add(new Arvore("Xixá","Sterculia chichá","Sterciliaceae",0.5));
        arvores.add(new Arvore("Zolernia","Zollernia ilicifolia","Leguminosae-Papilionoideae",0.5));
        arvores.add(new Arvore("Abacateiro-do-mato","Persea pyrifolia","Lauraceae",0.7));
        arvores.add(new Arvore("Araucária","Araucaria angustifolia","Araucariaceae",0.7));
        arvores.add(new Arvore("Eucalipto","Eucaliptus toreliana","Myrtaceae",0.7));
        arvores.add(new Arvore("Eucalipto dunni","Eucalipto-dunni","Myrtaceae",0.7));
        arvores.add(new Arvore("Eucalipto grandis","Eucalyptus grandis","Myrtaceae",0.7));
        arvores.add(new Arvore("Eucaliptos vermelho","Eucaliptos ficifolia","Myrtaceae",0.7));
        arvores.add(new Arvore("Eucalypto Saligna","Eucalyptus Saligna"," Myrtaceae",0.7));
        arvores.add(new Arvore("Eucalyptus Limâo","Eucaliptus citriodora","Myrtaceae",0.7));
        arvores.add(new Arvore("Manga-brava","Swartzia macrostachya","Leguminosae-Papilionoideae",0.7));
        arvores.add(new Arvore("Pinheirinho","Podocarpus lamberti","Podocarpaceae",0.7));
        arvores.add(new Arvore("Pinheiro-bravo","Podocarpus lambertii","Podocarpaceae",0.7));
        arvores.add(new Arvore("Pinheiro-do-brejo","Taxodium distichum","Taxodiaceae",0.7));
        arvores.add(new Arvore("Pinheiro-do-paraná","Araucária angustifolia","Araucareaceae",0.7));
        arvores.add(new Arvore("Pinheiro-portugues","Cupressus lusitanicos","Cupressaceae",0.7));
        arvores.add(new Arvore("Pinheiro-portugues","Pinus caribaea","Pinaceae",0.7));
        arvores.add(new Arvore("Pinus-caribaea","Pinus elliotti","Pinaceae",0.7));
        arvores.add(new Arvore("Pinus-taeda","Pinus taeda","Pinaceae",0.7));
        arvores.add(new Arvore("Rabo-de-bugio","Dalbergia ecastophyllum Pell","Fabaceae",0.5));
        arvores.add(new Arvore("Angico vermelho","Parapiptadenia rigida","Fabaceae",0.5));
        arvores.add(new Arvore("Guajuvira","Patagonula americana","Boraginaceae",0.5));
        arvores.add(new Arvore("Mamica-de-cadela","Zanthoxylum rhoifolium Lam","Rutaceae",0.5));
        arvores.add(new Arvore("Camboatá vermelho","Cupania vernalis Cambess","Sapindaceae",0.5));
    }

    public static void build(Context context) {
        ArvoreDAO arvoreDAO = new ArvoreDAO(context);
        if (!arvoreDAO.hasArvores()) {
            for (Arvore a : arvores) {
                arvoreDAO.salvar(a);
            }
        }
    }

}
